spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://172.168.1.100/authentication
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

