spring:
  datasource:
    url: jdbc:mysql://172.168.1.1/authentication?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: toor
  jpa :
    show-sql: true
    database: mysql
system:
  passwordSetting:
    algorithmName: md5
    hashIterations: 2
  filterChain: >
    {
      "/api/main/**": "anon",
      "/static/**": "anon" ,
      "/logout":"logout",
      "/**":"authc"
    }
  loginUrl: /login
  unauthorizedUrl: /403

