spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authentication?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa :
    show-sql: true
    database: mysql
system:
  passwordSetting:
    algorithmName: md5
    hashIterations: 2
  session:
    cookieName: JUPITER
    headerName: JUPITER
    cacheKeyPrefix: JUPITER
    urlSessionId: false
    timeout: 1800000  #mills
  filterChain: >
    {
      "/callback" : "callback",
      "/api/log/**": "anon",
      "/static/**": "anon" ,
      "/assets/**": "anon" ,
      "/logout":"logout",
      "/**":"authc"
    }
  loginUrl: /api/log/login
  unauthorizedUrl: /403
redisson:
  enable: true
  address: "redis://127.0.0.1:6379"
  timeout: 1000
  poolSize: 5
  minIdleSize: 3
  database: 6
logging:
  level:
    root: debug

