spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/authentication?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa :
    show-sql: true
    database: mysql
system:
  password:
    algorithmName: md5
    hashIterations: 2
  filterChain: >
    {
      "/api/user/login.json": "anon",
      "/static/**": "anon" ,
      "/logout":"logout",
      "/**":"authc"
    }
  loginUrl: /login
  unauthorizedUrl: /403

