spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authentication?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa :
    show-sql: true
    database: mysql
system:
  passwordSetting:
    algorithmName: md5
    hashIterations: 2
  session:
    cookieName: JUPITER
    headerName: JUPITER
    cacheKeyPrefix: JUPITER
    urlSessionId: false
    timeout: 1800000  #mills
  filterChain: >
    {
      "/api/main/**": "anon",
      "/static/**": "anon" ,
      "/logout":"logout",
      "/**":"authc"
    }
  loginUrl: /login
  unauthorizedUrl: /403
redisson:
  enable: true
  address: "redis://127.0.0.1:6379"
  timeout: 1000
  poolSize: 5
  minIdleSize: 3
  database: 6

